framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction
            command.bus.async:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction
            query.bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection
                    - doctrine_transaction
            event.bus:
                default_middleware: allow_no_handlers
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        transports:
            sync: 'sync://'
            command.async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed&auto_setup=0'

        routing:
            App\Shared\Domain\Command\AsyncCommandInterface: command.async
            App\Shared\Domain\Command\CommandInterface: sync
            App\Shared\Domain\Query\QueryInterface: sync

when@test:
    framework:
        messenger:
            transports:
                command.async: 'test://'
